schema = "ailang.package.v1"
name = "ailang"
repo = "https://github.com/AiLangCore/AiLang.git"
packageRoot = "."
license = "MIT"
types = ["library", "tool", "template"]
defaultVersion = "0.0.1-alpha.29"

[versions."0.0.1-alpha.29"]
ref = "develop"
commit = "1a1a0c79c3836c4aee7c17127163a909a351c253"

[versions."0.0.1-alpha.28"]
ref = "develop"
commit = "b1ece871871f4a1e988b4536ec9eed0714c4076e"

[versions."0.0.1-alpha.27"]
ref = "develop"
commit = "a776b8f4d64d471ed927214caf4f48f6ee9ddd6b"

[versions."0.0.1-alpha.26"]
ref = "develop"
commit = "608eff3af60408266b1b7782cc53e720a64b9813"

[versions."0.0.1-alpha.25"]
ref = "v0.0.1-alpha.25"
commit = "b82b773dcb54ed170e8affe4b73bceda59a5e826"

[versions."0.0.1-alpha.24"]
ref = "v0.0.1-alpha.24"
commit = "dabf6bc931d04fbfd80e1a005d28db46e482e087"
