schema = "ailang.package.v1"
name = "std-app"
repo = "https://github.com/AiLangCore/ailang-core-packages.git"
packageRoot = "packages/std-app"
license = "MIT"
types = ["library"]
defaultVersion = "0.0.1-alpha.3"

[versions."0.0.1-alpha.3"]
ref = "main"
commit = "94b93fca9854dc31c739ceee5d6c893872ba8b4c"

[versions."0.0.1-alpha.2"]
ref = "main"
commit = "9bf08c87eac18d8b3d8f94f9a2254c1f71f67802"

[versions."0.0.1-alpha.1"]
ref = "main"
commit = "620fa313cc21b548e22b4fc3a654d4e99d87b1e8"
