schema = "ailang.package.v1"
name = "std-ui-input"
repo = "https://github.com/AiLangCore/ailang-core-packages.git"
packageRoot = "packages/std-ui-input"
license = "MIT"
types = ["library"]
defaultVersion = "0.0.1-alpha.5"

[versions."0.0.1-alpha.5"]
ref = "main"
commit = "8ec5adb5fe620d1133973b263fe64c592012da5a"

[versions."0.0.1-alpha.4"]
ref = "main"
commit = "f7c326033f9cca233a5c8c2d066f9549fb8e47af"

[versions."0.0.1-alpha.3"]
ref = "main"
commit = "a869fd4ea14c0461d6fcec7e76017217fd1cbfdb"

[versions."0.0.1-alpha.2"]
ref = "main"
commit = "3515bdfb0a9f70bee55d5f014811030bb61dcba4"

[versions."0.0.1-alpha.1"]
ref = "v0.0.1-alpha.1"
commit = "4cefe146e6ddabe3951f4fecf82facf36fdbde1a"
