schema = "ailang.package.v1"
name = "std-http"
repo = "https://github.com/AiLangCore/ailang-core-packages.git"
packageRoot = "packages/std-http"
license = "MIT"
types = ["library"]

[versions."0.0.1-alpha.1"]
ref = "v0.0.1-alpha.1"
commit = "4cefe146e6ddabe3951f4fecf82facf36fdbde1a"
