schema = "ailang.package.v1"
name = "target-wasm"
repo = "https://github.com/AiLangCore/ailang-target-wasm.git"
packageRoot = "packages/target-wasm"
license = "MIT"
types = ["target", "tool", "template"]
defaultVersion = "0.0.1-alpha.3"

[versions."0.0.1-alpha.3"]
ref = "main"
commit = "e466b5b0c4e0eaf5579e9f3df27f4fe8b2cf2e00"

[versions."0.0.1-alpha.1"]
ref = "main"
commit = "9966b21a19049944ce9055b3fa22fbd0b11328ba"

[versions."0.0.1-alpha.2"]
ref = "main"
commit = "a6b67bfbf1abfc091cf76a49c356d8ce2a48a7c6"
