schema = "ailang.package.v1"
name = "target-macos"
repo = "https://github.com/AiLangCore/ailang-target-macos.git"
packageRoot = "packages/target-macos"
license = "MIT"
types = ["target", "tool", "template"]
defaultVersion = "0.0.1-alpha.2"

[versions."0.0.1-alpha.1"]
ref = "main"
commit = "785a251ebf30b2d5b3d75bf9f43c88f9935687de"

[versions."0.0.1-alpha.2"]
ref = "main"
commit = "65056a6437b565c2c125571259980846c8d156f0"
