schema = "ailang.package.v1"
name = "target-linux"
repo = "https://github.com/AiLangCore/ailang-target-linux.git"
packageRoot = "packages/target-linux"
license = "MIT"
types = ["target", "tool", "template"]
defaultVersion = "0.0.1-alpha.5"

[versions."0.0.1-alpha.5"]
ref = "main"
commit = "7288136516e7d7ec5ae781238b2d59835fa51e61"

[versions."0.0.1-alpha.4"]
ref = "main"
commit = "9955554db00c5f0cff4e11a0c6ee19228861e606"

[versions."0.0.1-alpha.3"]
ref = "main"
commit = "530d0b83d67a82aa4d4d3f1a69d33d692fe8c899"

[versions."0.0.1-alpha.1"]
ref = "main"
commit = "44ef5e0b95d9663ccf11580ebf502d0ed8c22b80"

[versions."0.0.1-alpha.2"]
ref = "main"
commit = "f0553ea6c041f7f8c3dc1548a78ca33382b0dbf3"
