schema = "ailang.package.v1"
name = "target-aios-gui"
repo = "https://github.com/AiLangCore/ailang-core-packages.git"
packageRoot = "packages/target-aios-gui"
license = "MIT"
types = ["target", "tool", "template"]
defaultVersion = "0.0.1-alpha.1"

[versions."0.0.1-alpha.1"]
ref = "main"
commit = "4b72566072ad626ff80787047d2736f9c7af062e"
