schema = "ailang.package.v1"
name = "target-windows"
repo = "https://github.com/AiLangCore/ailang-target-windows.git"
packageRoot = "packages/target-windows"
license = "MIT"
types = ["target", "tool", "template"]
defaultVersion = "0.0.1-alpha.1"

[versions."0.0.1-alpha.1"]
ref = "main"
commit = "08db3ac2d49fdeb13e693844de79ba8ac8d6de9e"
