schema = "ailang.package.v1"
name = "target-aios-gui"
repo = "https://github.com/AiLangCore/ailang-core-packages.git"
packageRoot = "packages/target-aios-gui"
license = "MIT"
types = ["target", "tool", "template"]
defaultVersion = "0.0.1-alpha.1"

[versions."0.0.1-alpha.1"]
ref = "main"
commit = "dbb7ca5191d565a8c8f6b9b8258e4372a4d83898"
