schema = "ailang.package.v1"
name = "target-aios-service"
repo = "https://github.com/AiLangCore/ailang-target-aios.git"
packageRoot = "packages/target-aios-service"
license = "MIT"
types = ["target", "tool", "template"]
defaultVersion = "0.0.1-alpha.4"

[versions."0.0.1-alpha.1"]
ref = "main"
commit = "01d4ec284cd2158c9b0adf0a7e5167186ad68975"

[versions."0.0.1-alpha.2"]
ref = "v0.0.1-alpha.2"
commit = "eb7d35aaab27d13a271e4f04f2646dd3b3475262"

[versions."0.0.1-alpha.3"]
ref = "v0.0.1-alpha.3"
commit = "d74f8723c9db778ca2c456d27563bf03285ca931"

[versions."0.0.1-alpha.4"]
ref = "v0.0.1-alpha.4"
commit = "942065a46986a970a30d4a52e9396d8aae938470"
