schema = "ailang.package.v1"
name = "target-aios-service"
repo = "https://github.com/AiLangCore/ailang-core-packages.git"
packageRoot = "packages/target-aios-service"
license = "MIT"
types = ["target", "tool", "template"]
defaultVersion = "0.0.1-alpha.1"

[versions."0.0.1-alpha.1"]
ref = "main"
commit = "ee8c934e5cddde443ce3dd8a63433100fd6933fd"
