schema = "ailang.package.v1"
name = "target-aios-gui"
repo = "https://github.com/AiLangCore/ailang-core-packages.git"
packageRoot = "packages/target-aios-gui"
license = "MIT"
types = ["target", "tool", "template"]
defaultVersion = "0.0.1-alpha.1"

[versions."0.0.1-alpha.1"]
ref = "main"
commit = "029aaa6eb4c0a48c93f19a7bc774b64be0b789f7"
